// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimSetupManager.Api.Data;

#nullable disable

namespace SimSetupManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimSetupManager.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SimSetupManager.Core.Entities.Setup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Setups");
                });

            modelBuilder.Entity("SimSetupManager.Core.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Name")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Variante")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SimSetupManager.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Brand")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Model")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Variante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Year")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SimSetupManager.Core.Entities.Setup", b =>
                {
                    b.OwnsOne("SimSetupManager.Core.Entities.EnvironmentCondition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("SetupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("AirTemp")
                                .HasColumnType("float")
                                .HasColumnName("Condition_AirTemp");

                            b1.Property<string>("TimeOfDay")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Condition_TimeOfDay");

                            b1.Property<double>("TrackTemp")
                                .HasColumnType("float")
                                .HasColumnName("Condition_TrackTemp");

                            b1.Property<string>("Weather")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Condition_Weather");

                            b1.HasKey("SetupId");

                            b1.ToTable("Setups");

                            b1.WithOwner()
                                .HasForeignKey("SetupId");
                        });

                    b.Navigation("Conditions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
